"""Pydantic models for market data and agent outputs.

Ported verbatim (field-for-field) from the legacy ``stratton/src/data/models.py``
so the persona/analyst logic — and the Phase-0 golden parity fixtures generated
against those models — reproduce bit-for-bit. The only change is the module home
(``app.engine.models``); no field names, types, or defaults were altered.
"""
from __future__ import annotations

from datetime import date, datetime
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator


# ── Market Data Models ──────────────────────────────────────────────


class Price(BaseModel):
    """Single OHLCV bar."""
    open: float
    high: float
    low: float
    close: float
    volume: float
    timestamp: datetime
    vwap: Optional[float] = None
    transactions: Optional[int] = None


class FinancialMetrics(BaseModel):
    """Key financial metrics for one reporting period."""
    ticker: str
    period: str
    fiscal_period: str
    filing_date: Optional[date] = None
    revenue: Optional[float] = None
    net_income: Optional[float] = None
    earnings_per_share: Optional[float] = None
    total_assets: Optional[float] = None
    total_liabilities: Optional[float] = None
    shareholders_equity: Optional[float] = None
    operating_cash_flow: Optional[float] = None
    free_cash_flow: Optional[float] = None
    gross_profit_margin: Optional[float] = None
    net_profit_margin: Optional[float] = None
    return_on_equity: Optional[float] = None
    debt_to_equity: Optional[float] = None
    current_ratio: Optional[float] = None


class CompanyNews(BaseModel):
    """A single news article."""
    title: str
    author: Optional[str] = None
    published_utc: datetime
    article_url: str
    description: Optional[str] = None
    tickers: list[str] = Field(default_factory=list)


class CompanyDetails(BaseModel):
    """Ticker reference details."""
    ticker: str
    name: str
    market_cap: Optional[float] = None
    description: Optional[str] = None
    sic_code: Optional[str] = None
    sic_description: Optional[str] = None
    homepage_url: Optional[str] = None
    total_employees: Optional[int] = None
    list_date: Optional[str] = None
    share_class_shares_outstanding: Optional[float] = None
    weighted_shares_outstanding: Optional[float] = None


# ── Agent Output Models ─────────────────────────────────────────────


class SignalType(str, Enum):
    """Trading signal direction."""
    BULLISH = "bullish"
    BEARISH = "bearish"
    NEUTRAL = "neutral"


class AnalystSignal(BaseModel):
    """Signal generated by an analyst/persona agent for a single ticker."""
    agent_id: str
    ticker: str
    signal: SignalType
    confidence: float = Field(ge=0, le=100, description="Confidence 0-100")
    reasoning: str


class LLMAnalysisResult(BaseModel):
    """Structured output from LLM-powered reasoning (synthesis)."""
    signal: SignalType = Field(description="Trading signal: bullish, bearish, or neutral")
    confidence: Any = Field(description="Confidence level 0-100")
    reasoning: str = Field(description="2-4 sentence explanation citing specific data points. Be concise.")

    @field_validator("confidence", mode="before")
    @classmethod
    def coerce_confidence(cls, v: Any) -> float:
        try:
            val = float(v)
            return max(0.0, min(100.0, val))
        except (ValueError, TypeError):
            return 0.0


class TradeAction(str, Enum):
    """Portfolio manager trade action."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class Position(BaseModel):
    """A single portfolio position decision."""
    ticker: str
    action: TradeAction
    quantity: int
    confidence: float = Field(ge=0, le=100)
    reasoning: str


class Portfolio(BaseModel):
    """Full portfolio output from the portfolio manager."""
    positions: list[Position] = Field(default_factory=list)
    cash_remaining: float = 0.0
    total_value: float = 0.0
